# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(750, 673)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(9, 10, 691, 677))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_3.setEnabled(True)
        self.radioButton_3.setObjectName("radioButton_3")
        self.verticalLayout_2.addWidget(self.radioButton_3)
        self.radioButton_2 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_2.setEnabled(True)
        self.radioButton_2.setObjectName("radioButton_2")
        self.verticalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_4 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_4.setEnabled(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.verticalLayout_2.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_5.setEnabled(True)
        self.radioButton_5.setObjectName("radioButton_5")
        self.verticalLayout_2.addWidget(self.radioButton_5)
        self.radioButton_6 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_6.setEnabled(True)
        self.radioButton_6.setObjectName("radioButton_6")
        self.verticalLayout_2.addWidget(self.radioButton_6)
        self.radioButton_9 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_9.setEnabled(True)
        self.radioButton_9.setObjectName("radioButton_9")
        self.verticalLayout_2.addWidget(self.radioButton_9)
        self.radioButton_8 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_8.setEnabled(True)
        self.radioButton_8.setObjectName("radioButton_8")
        self.verticalLayout_2.addWidget(self.radioButton_8)
        self.radioButton_7 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_7.setEnabled(True)
        self.radioButton_7.setObjectName("radioButton_7")
        self.verticalLayout_2.addWidget(self.radioButton_7)
        self.radioButton = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton.setEnabled(True)
        self.radioButton.setObjectName("radioButton")
        self.verticalLayout_2.addWidget(self.radioButton)
        self.radioButton_10 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_10.setObjectName("radioButton_10")
        self.verticalLayout_2.addWidget(self.radioButton_10)
        self.radioButton_11 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_11.setObjectName("radioButton_11")
        self.verticalLayout_2.addWidget(self.radioButton_11)
        self.radioButton_12 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_12.setObjectName("radioButton_12")
        self.verticalLayout_2.addWidget(self.radioButton_12)
        self.radioButton_13 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_13.setObjectName("radioButton_13")
        self.verticalLayout_2.addWidget(self.radioButton_13)
        self.radioButton_14 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_14.setObjectName("radioButton_14")
        self.verticalLayout_2.addWidget(self.radioButton_14)
        self.radioButton_15 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_15.setObjectName("radioButton_15")
        self.verticalLayout_2.addWidget(self.radioButton_15)
        self.radioButton_16 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_16.setObjectName("radioButton_16")
        self.verticalLayout_2.addWidget(self.radioButton_16)
        self.radioButton_17 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_17.setObjectName("radioButton_17")
        self.verticalLayout_2.addWidget(self.radioButton_17)
        self.radioButton_18 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_18.setObjectName("radioButton_18")
        self.verticalLayout_2.addWidget(self.radioButton_18)
        self.radioButton_19 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_19.setObjectName("radioButton_19")
        self.verticalLayout_2.addWidget(self.radioButton_19)
        self.radioButton_20 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_20.setObjectName("radioButton_20")
        self.verticalLayout_2.addWidget(self.radioButton_20)
        self.radioButton_21 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_21.setObjectName("radioButton_21")
        self.verticalLayout_2.addWidget(self.radioButton_21)
        self.radioButton_22 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButton_22.setObjectName("radioButton_22")
        self.verticalLayout_2.addWidget(self.radioButton_22)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 50))
        self.label.setAutoFillBackground(False)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_2.sizePolicy().hasHeightForWidth())
        self.lineEdit_2.setSizePolicy(sizePolicy)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_4 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_2.addWidget(self.pushButton_4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.radioButton_3.setText(_translate("Form", "Классика"))
        self.radioButton_2.setText(_translate("Form", "Современная проза"))
        self.radioButton_4.setText(_translate("Form", "Детские книги"))
        self.radioButton_5.setText(_translate("Form", "Бизнес книги"))
        self.radioButton_6.setText(_translate("Form", "Любовные романы"))
        self.radioButton_9.setText(_translate("Form", "Детективы"))
        self.radioButton_8.setText(_translate("Form", "Фантастика"))
        self.radioButton_7.setText(_translate("Form", "Фэнтези"))
        self.radioButton.setText(_translate("Form", "Религия"))
        self.radioButton_10.setText(_translate("Form", "Юмор"))
        self.radioButton_11.setText(_translate("Form", "Книги по психологии"))
        self.radioButton_12.setText(_translate("Form", "Наука, образование"))
        self.radioButton_13.setText(_translate("Form", "Справочники"))
        self.radioButton_14.setText(_translate("Form", "Публицистика"))
        self.radioButton_15.setText(_translate("Form", "Приключения"))
        self.radioButton_16.setText(_translate("Form", "Дом, семья"))
        self.radioButton_17.setText(_translate("Form", "Искусство"))
        self.radioButton_18.setText(_translate("Form", "Школьная литература"))
        self.radioButton_19.setText(_translate("Form", "Зарубежная литература"))
        self.radioButton_20.setText(_translate("Form", "Боевики"))
        self.radioButton_21.setText(_translate("Form", "Компьютеры"))
        self.radioButton_22.setText(_translate("Form", "Повести, рассказы"))
        self.label_3.setText(_translate("Form", "название:"))
        self.label_2.setText(_translate("Form", "имя автора:"))
        self.pushButton_3.setText(_translate("Form", "предыдущая"))
        self.pushButton_4.setText(_translate("Form", "следующая"))
        self.pushButton_2.setText(_translate("Form", "добавить книгу"))
